import Head from "next/head";

import styles from "../styles/Home.module.css";
import Header3 from "../components/Header3";
import Lobby from "../components/Lobby";
import Intro from "../components/Intro";
import Footer from "../components/Footer";
import ConnectWallet from "../components/ConnectWallet";

import React, { useContext } from "react";
import Web3Context from "../context/Web3Context";

import { useMoralis } from "react-moralis";
import ConnectChain from "../components/ConnectChain";
import ContactSectionOne from "../components/contact-section-one";
import { Chart } from "../components/Chart";

const supportedChains = ["31337", "11155111"] // test 31337 or remove it only sepolia is certain


export default function Home() {
  const {
    first,
    second,
    third,
    timeLeft,

  } = useContext(Web3Context);

  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div>
      <Head>
        <title>Online Safety Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header3 />
      <Intro />

      {isWeb3Enabled ? (
        <>
          {
            supportedChains.includes(parseInt(chainId).toString()) ? (
              <>
                <Lobby />
                {timeLeft && <Chart />}
              </>
            ) : (
              <ConnectChain />
            )
          }
        </>

      ) : (

        <ConnectWallet />
      )
      }

      <ContactSectionOne />
      <Footer />
    </div>
  );
}
