# Using Node 18.14 as the base image
FROM node:18.14

# Install dependencies required for running Cypress
RUN apt-get update \
    && apt-get install -y \
        libgtk2.0-0 \
        libgtk-3-0 \
        libgbm-dev \
        libnotify-dev \
        libgconf-2-4 \
        libnss3 \
        libxss1 \
        libasound2 \
        libxtst6 \
        xauth \
        xvfb

# Set the working directory to /app
WORKDIR /home/frontend


# Copy the remaining frontend code to the working directory
COPY frontend/. /home/frontend

# Run the tests
CMD ["yarn", "test"]
